/* Generated By:JavaCC: Do not edit this line. CParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int DIV = 11;
  /** RegularExpression Id. */
  int MUL = 12;
  /** RegularExpression Id. */
  int ADD = 13;
  /** RegularExpression Id. */
  int SUB = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"/*\"",
    "<token of kind 6>",
    "\"*/\"",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"/\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
